In [1]:
import numpy as np

# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [33]:
a = np.array([1.2, 5.4, 6, 1.59])
b = np.array([5.2, 1.2, 1.5, 2])
# sqrt
print("sqrt:", np.sqrt(a), np.sqrt(b))
# exp
print("exp:", np.exp(a / 2), np.exp(b / 2))
# sum
print("sum:", a + b)
# product
print("product:", a * b)
# linspace
print("linspace:", np.linspace(0, 30, 60, endpoint=False))
# linspace
print("linspace:", np.linspace(1, 2, 100))
# linspace 2x6
print("linspace 2x6:", np.array((np.linspace(10, 20, 6), np.linspace(20, 10, 6))))
# dot
print("dot:", np.dot(a, b))
# matrix
A = np.array((a, b))
print("matrix:", A)
# dot
print("dot:", np.dot(A[0], A[1]))
# matrix dot
print("matrix dot:", np.dot(A, b))
# diagonal
print("diagonal:", np.diag(a))

sqrt: [1.09544512 2.32379001 2.44948974 1.26095202] [2.28035085 1.09544512 1.22474487 1.41421356]
exp: [ 1.8221188  14.87973172 20.08553692  2.214441  ] [13.46373804  1.8221188   2.11700002  2.71828183]
sum: [6.4  6.6  7.5  3.59]
product: [6.24 6.48 9.   3.18]
linspace: [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5]
linspace: [1.         1.01010101 1.02020202 1.03030303 1.04040404 1.05050505
 1.06060606 1.07070707 1.08080808 1.09090909 1.1010101  1.11111111
 1.12121212 1.13131313 1.14141414 1.15151515 1.16161616 1.17171717
 1.18181818 1.19191919 1.2020202  1.21212121 1.22222222 1.23232323
 1.24242424 1.25252525 1.26262626 1.27272727 1.28282828 1.29292929
 1.3030303  1.31313131 1.32323232 1.33333333 1.34343434 1.35353535
 1.36363636

# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [84]:
# A
A = np.hstack((
    np.full((3, 3), 2),
    np.full((3, 1), 3)
))
print("A:\n", A)
# B
B = np.hstack((
    np.eye(3, 3, dtype=int) * 2,
    np.full((3, 10), np.arange(10) + 1)
))
print("B:\n", B)
# C
C = np.eye(5, 5, 1, dtype=int) * -1 \
    + np.eye(5, 5, dtype=int) * 2 \
    + np.eye(5, 5, -1, dtype=int) * -1
print("C:\n", C)
# D
D = np.vstack((
    np.hstack((
        np.full((2, 2), 2),
        np.full((2, 2), 3)
    )),
    np.diagflat([[0, 0], [5, 5]])
))
print("D:\n", D)

A:
 [[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
B:
 [[ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]]
C:
 [[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
D:
 [[2 2 3 3]
 [2 2 3 3]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 5 0]
 [0 0 0 5]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [90]:
N = 5
arr = [a for a in range(N * 2) if a % 2 == 1]
sum(arr)
np.sum(arr)

25

# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

Ricordiamo la formula per generare i i numeri di Fibonacci:

$$F_0=1$$
$$F_1=1$$
$$F_n = F_{n-1} + F_{n-2}, \quad n=2,...$$