## Esercitazione 8  del    23 Aprile 2024


## Condizionamento del problema della soluzione di un sistema lineare

In [1]:
import numpy as np
import scipy as sp
import scipy.linalg as spl
import numpy.linalg as npl
from  SolveTriangular import *

# Esercizio 1
- Costruire la matrice di Vandermonde A, generata dal vettore x=[1.0,2.0,...,6.0] utilizzando la funzione np.vander(x, increasing=True) di numpy. 
- Calcolarne l'indice di condizionamento in norma infinito senza utilizzare la funzione cond di numpy.linalg e poi confrontarne il valore con quello ottenuto utilizzando la funzione.
- Considerare il sistema lineare Ax=b  con matrice dei coefficienti A e termine noto costruito in maniera tale che la soluzione esatta sia il vettore x=[1,1,1,1,1,1] (ogni sua componente è 1) e risolverlo usando il metodo solve del modulo linalg di Scipy.
- perturbare il vettore dei termini noti della quantità
$$
\delta b = 0.025 \, \ast \,
\left [
\begin{array}{c}
1\\
0\\
0\\
0
\end{array}
\right ]
$$
- Risolvere il sistema con termine noto pertubato $b + \delta b$ ((usando il metodo solve del modulo linalg di Scipy).
- Calcolare l'errore relativo sul termine noto e l'errore relativo sulla soluzione. Cosa si può concludere?

N.B. per il calcolo dell'inversa della matrice di A usare la funzione di numpy.linalg.inv(A).


In [42]:
x = np.arange(1.0, 7.0)
A = np.vander(x, increasing=True)

In [41]:
# termini noti uguali alla somma dei coefficienti
# la soluzione sarà tutti 1
b = np.sum(A, axis=1).reshape(6, 1)
x = spl.solve(A, b)
print("soluzione:", x)

soluzione: [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [38]:
# perturbo b
bp = b.copy()
bp[0] = bp[0] + 0.025

# calcolo errore relativo sui dati
errore_dati = npl.norm(bp - b, np.inf) / npl.norm(b, np.inf)
print("errore relativo sui dati:", errore_dati)

errore relativo sui dati: 2.679241238881187e-06


In [44]:
# calcolo errore relativo sulla soluzione
xp = spl.solve(A, bp)
errore_soluzione = npl.norm(xp - x, np.inf) / npl.norm(x, np.inf)

print("soluzione:", xp)
print("errore relativo sulla soluzione:", errore_soluzione)

soluzione: [[1.15      ]
 [0.7825    ]
 [1.12083333]
 [0.96770833]
 [1.00416667]
 [0.99979167]]
errore relativo sulla soluzione: 2.7174999999923224


In [51]:
# si vede che il problema è mal condizionato
# calcolo indice di condizionamento
KA = npl.cond(A, np.inf)
print("K(A):", KA)

K(A): 1204321.0666666434


## Esercizio 2
Assegnato il sistema lineare $Ax = b$, con
$$
A =
\left [
\begin{array}{ccc}
6 & 63 & 662.2\\
63 & 662.2 & 6967.8\\
662.2 & 6967.8 & 73393.5664
\end{array}
\right ], \qquad
b =
\left [
\begin{array}{c}
1.1\\
2.33\\
1.7
\end{array}
\right ]
$$
- trovare il vettore soluzione $x$ (usando il metodo solve del modulo linalg di Scipy);
- perturbare la matrice dei coefficienti della quantità
$$
\delta A =
0.01 \, \ast \,
\left [ \begin{array}{ccc}
1 & 0 & 0\\
0 & 0 & 0\\
0 & 0 & 0
\end{array}
\right ]
$$
quindi calcolare l'errore relativo sulla soluzione e confrontarlo con la
perturbazione relativa sui dati di ingresso. Cosa si osserva?

In [68]:
A = np.array([
    [6, 63, 662.2],
    [63, 662.2, 6967.8],
    [662.2, 6967.8, 73393.5664]
])
b = np.array([1.1, 2.33, 1.7]).reshape(3, 1)

In [69]:
# calcolo soluzione del sistema
x = spl.solve(A, b)
print("soluzione:", x)

soluzione: [[136422.33746479]
 [-25999.49954686]
 [  1237.44419611]]


In [100]:
# perturbo la matrice dei coefficenti
dA = np.zeros((3, 3))
dA[0][0] = 1 * 0.01
Ap = A + dA

# calcolo errore relativo sui dati
errore_dati = npl.norm(dA, np.inf) / npl.norm(A)
print("errore relativo sui dati:", errore_dati)

errore relativo sui dati: 0.0005431254465935684


In [81]:
# calcolo soluzione perturbata e errrore relativo
xp = spl.solve(Ap, b)
errore_soluzione = npl.norm(x - xp, np.inf) / npl.norm(x, np.inf)

print("soluzione perturbata:", xp)
print("errore relativo sulla soluzione:", errore_soluzione)

soluzione perturbata: [[67.09867276]
 [-9.66739506]
 [ 0.3124175 ]]
errore relativo sulla soluzione: 0.9995081547933965


## Esercizio 3
 
Assegnato il sistema lineare $Ax = b$, con $A$ matrice di Hilbert di ordine
$4$ e $b = [1, 1, 1, 1]^T$,
 - trovare il vettore soluzione $x$ (usando il metodo solve del modulo linalg di Scipy);
 -  perturbare il vettore dei termini noti della quantità
$$
\delta b = 0.01 \, \ast \,
\left [
\begin{array}{c}
1\\
-1\\
1\\
-1
\end{array}
\right ]
$$
quindi calcolare la soluzione del sistema $A x_p= b_p$ con termine noto $b_p=b+ \delta b$.
Calcolare l'errore relativo sulla soluzione e confrontarlo con la perturbazione relativa sui dati di ingresso. Cosa si osserva?

Nota: per la costruzione della matrice di Hilbert usare la funzione hilbert(n) del modulo scipy.linalg
(scipy.linalg.hilbert(n))  dove bisogna specificare l'ordine n della matrice.

In [64]:
n = 4
b = np.full((n, 1), 1)
# Aij = 1/(i+j-1)  con i,j=1,...,n
A = spl.hilbert(4)

print("A:", A)

A: [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]


In [56]:
# calcolo soluzione
x = spl.solve(A, b)
print("soluzione:", x)

soluzione: [[  -4.]
 [  60.]
 [-180.]
 [ 140.]]


In [65]:
# calcolo delta b e b perturbato
db = np.array([1, -1, 1, -1]).reshape(4, 1) * 0.01
bp = b.copy()
bp = b + db
print("b perturbato:", bp)

# calcolo errore relativo sui dati
errore_dati = npl.norm(db, np.inf) / npl.norm(b)
print("errore relativo sui dati:", errore_dati)

b perturbato: [[1.01]
 [0.99]
 [1.01]
 [0.99]]
errore relativo sui dati: 0.005


In [66]:
# calcolo soluzione perturbata e errrore relativo
xp = spl.solve(A, bp)
errore_soluzione = npl.norm(x - xp, np.inf) / npl.norm(x, np.inf)

print("soluzione perturbata:", xp)
print("errore relativo sulla soluzione:", errore_soluzione)

soluzione perturbata: [[  1.16]
 [  3.  ]
 [-43.8 ]
 [ 51.8 ]]
errore relativo sulla soluzione: 0.7566666666666719


## Metodi diretti per la soluzione numerica di un sistema lineare

## Nota 1.
La funzione *scipy.linalg.lu(A)*  , presa in input una matrice A a rango massimo, restituisce in output le matrici $P^T$,L,U,  della fattorizzazione di LU della matrice A in maniera tale che PA=LU (restituisce la matrice di permutazione trasposta)

In [1]:
A = np.array([[2,1],[3,4]])
PT, L , U = spl.lu(A) # Restituisce in output la trasposta della matrice di Permutazione
P = PT.T.copy() # P è la matrice di permutazione
print("A=", A)
print("L=", L)
print("U=", U)
print("P=", P)

# LU è la fattorizzazione di P*A (terorema 2)
A1 = P @ A # equivale al prodotto matrice x matrice np.dot(P,A)
A1Fatt = L @ U # equivale a np.dot(L,U)
print("Matrice P*A \n", A1)
print("Matrice ottenuta moltipicando Le ed U \n", A1Fatt)


A= [[2 1]
 [3 4]]
L= [[1.         0.        ]
 [0.66666667 1.        ]]
U= [[ 3.          4.        ]
 [ 0.         -1.66666667]]
P= [[0. 1.]
 [1. 0.]]
Matrice P*A 
 [[3. 4.]
 [2. 1.]]
Matrice ottenuta moltipicando Le ed U 
 [[3. 4.]
 [2. 1.]]


## Nota 2
La funzione *scipy.linalg.cholesky(a, lower=True)*, presa in input una matrice simmetrica e definta positiva restituisce in output la matrice L triangolare inferiore tale che $A=L \cdot L^T$. Se la matrice in input non è definita positiva, restituisce un errore.

In [38]:
A = np.array([[2,1,3],[1,5,7],[3,7,12]])
print(A)

[[ 2  1  3]
 [ 1  5  7]
 [ 3  7 12]]


In [39]:
L = spl.cholesky(A,lower=True)
print(L)
A1 = L @ L.T
print("A1=\n",A1)

[[1.41421356 0.         0.        ]
 [0.70710678 2.12132034 0.        ]
 [2.12132034 2.59272486 0.8819171 ]]
A1=
 [[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Nota 3
La funzione *scipy.linalg.qr(a)*, presa in input una matrice A (nxn)  a rango massimo, restituisce in output le matrici Q (ortogonale di dimensione nxn) ed una matrice R (nxn) triangolare superiore tale che $A=Q \cdot R$

In [40]:
A = np.array([[2,1,3],[1,5,7],[3,7,12]])
Q, R = spl.qr(A)
print("Q=", Q)
print("R=", R)
A1 = Q @ R
print(A1)

Q= [[-0.53452248  0.6882472  -0.49051147]
 [-0.26726124 -0.6882472  -0.67445327]
 [-0.80178373 -0.22941573  0.55182541]]
R= [[ -3.74165739  -7.48331477 -13.09580085]
 [  0.          -4.35889894  -5.50597761]
 [  0.           0.           0.42919754]]
[[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Esercizio 4
- si implementi una function LUsolve(P,A,L,U,b) che risolve il sistema lineare Ax=b nel caso di fattorizzazione $PA = LU$ assegnata,
combinando i metodi di risoluzione in avanti ed all'indietro  implementati nel file SolveTriangular.py.
- si testi sulla matrice A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]]) con termine noto b scelto in maniera tale che la soluzione esatta del sistema lineare sia il vettore formato da tutti 1.

In [92]:
"""
risolve il sistema
triangolare inferirore: Ly = Pb
trianfolare superiore: Ux = y
"""
def LUsolve(P, A, L, U, b):
    y, flag = Lsolve(L, P @ b)
    if flag == 0:
        return Usolve(U, y)
    else:
        return None, None

soluzione: [[1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
#  b scelto in maniera tale che la soluzione esatta del sistema lineare sia il vettore formato da tutti 1.
b = np.sum(A, axis=1).reshape(4, 1)

PT, L, U = spl.lu(A) # calcola la fattorizzazone LU della matrice PA
P = PT.T.copy() # restituisce la matrice di permutazione trasposta
x, flag = LUsolve(P, A, L, U, b)

print("soluzione:", x)

## Esercizio 5
Si implementi una function *solve_nsis(A,B)* per il calcolo della soluzione di un generale sistema lineare $AX = B$, con $X, B$ matrici, che usi la fattorizzazione LU della matrice PA, per risolvere n sistemi lineari: aventi la stessa matrice dei coefficienti A e termine noto l'i-esima colonna della matrice B. 
Utilizzarla poi per il calcolo dell'inversa delle
matrici non singolari
$$
A=\left[
\begin{array}{ccc}
3 & 5 & 7\\
2 & 3 & 4\\
5 & 9 & 11
\end{array}
\right ], \qquad
A=\left[
\begin{array}{cccc}
1 & 2 & 3 & 4\\
2 & -4 & 6 & 8\\
-1 & -2 & -3 & -1\\
5 & 7 & 0 & 1
\end{array}
\right ],
$$
confrontando i risultati ottenuti con l'output
della funzione  *scipy.linalg.inv(A)*

In [141]:
"""
risolve n sistemi dati dalla matrice B
"""
def solve_nsis(A: np.matrix, B: np.matrix):
    solves = np.zeros(A.shape)
    
    # fattorizzo A
    PT, L, U = spl.lu(A) # calcola la fattorizzazone LU della matrice PA
    P = PT.T.copy() # restituisce la matrice di permutazione trasposta
    
    for i in range(len(B)):
        b = B[:,i] # i-esima colonna
        x, flag = LUsolve(P, A, L, U, b)
        solves[:,i] = x.reshape(3,) # assegno x alla i-esima colonna delle soluzioni
        
    return solves

A = np.array([
    [3, 5, 7],
    [2, 3, 4],
    [5, 9, 11]
])
B = np.identity(A.shape[0])

x = solve_nsis(A, B)
inv = spl.inv(A)
print("soluzione:", x)
print("inv:", inv)

soluzione: [[-1.5  4.  -0.5]
 [-1.  -1.   1. ]
 [ 1.5 -1.  -0.5]]
inv: [[-1.5  4.  -0.5]
 [-1.  -1.   1. ]
 [ 1.5 -1.  -0.5]]


## Esercizio 6
Sfruttando la fattorizzazione PA=LU  di una delle matrici del punto precedente, calcolarne il determinante.


In [20]:
A = np.array([
    [3, 5, 7],
    [2, 3, 4],
    [5, 9, 11]
])
A.astype(float)

array([[ 3.,  5.,  7.],
       [ 2.,  3.,  4.],
       [ 5.,  9., 11.]])

In [25]:
PT, L, U = spl.lu(A) # calcola la fattorizzazone LU della matrice PA
P = PT.T.copy() # restituisce la matrice di permutazione trasposta

s = 1
detA = -1**s * U.diagonal().prod()
print("detA:", detA)
print("detA:", npl.det(A))

detA: 1.9999999999999996
detA: 1.9999999999999996


## Esercizio 7
Per valori di $n = 4 : 6 : 40$, si consideri il sistema lineare $A_n x = b$ con
$A_n$ matrice di Hankel di ordine $n$ di elementi
$$
a^{(n)}_{i,n+k-i}
=
\left \{
\begin{array}{ll}
2^k & \hbox{se} \ k > 0,\\
2^{1/(2-k)} & \hbox{se} \ k \leq 0,
\end{array}
\right .
\qquad
i = 1, ..., n, \ \  k = i + 1-n, ..., i,
$$
e $b$ scelto in modo che risulti $x = [1, 1, ..., 1]^T$. Si risolva tale sistema
con il metodo di fattorizzazione LU della matrice PA
e il metodo di fattorizzazione QR (Q,R  =scipy.linalg.qr(A)).
Calcolare gli errori relativi $\| \delta x \|_2/\|x\|_2$ da cui sono affette
le soluzioni calcolate con i due metodi e produrre, al variare di $n$, un
grafico in scala logaritmica ( matplotlib.plyplot.loglog) degli errori relativi calcolati. Che cosa si
osserva?

NB: per il calcolo della matrice di Hankel utilizzare la function 

In [93]:
def Hankel(n):
    A = np.zeros((n,n),dtype=float)
    for i in range(0,n):
        for k in range(i+1-n,i+1):
            if k > 0:
                A[i,n-1+k-i] = 2.0**(k+1)
            else:
                A[i,n-1+k-i] = 2.0**(1/(2-k-1))
    return A

In [144]:
n = 4
A = Hankel(n)
b = np.sum(A, axis=1).reshape(n, 1)
x = np.full((n, 1), 1.0).reshape(n, 1)

print("A:", A)
print("b:", b)
print("x:", x)

A: [[ 1.18920712  1.25992105  1.41421356  2.        ]
 [ 1.25992105  1.41421356  2.          4.        ]
 [ 1.41421356  2.          4.          8.        ]
 [ 2.          4.          8.         16.        ]]
b: [[ 5.86334173]
 [ 8.67413461]
 [15.41421356]
 [30.        ]]
x: [[1.]
 [1.]
 [1.]
 [1.]]


In [145]:
PT, L, U = spl.lu(A)
P = P.T.copy()

xlu, flag = LUsolve(P, A, L, U, b)
print("solve LU:", xlu)

errore_lu = npl.norm(x - xlu, 2) / npl.norm(x, 2)
print("errore lu:", errore_lu)

solve LU: [[  3.68475241]
 [ 25.21781018]
 [ 15.18888631]
 [-13.81735634]]
errore lu: 15.926305040139134


In [ ]:
Q, R = spl.qr(A)
A1 = Q @ R
print(A1)

## Esercizio 8

Ripetere l'esercizio precedente per risolvere il sistema lineare $Ax = b$
con $A$ e $b$ cos\`i  definiti:
$$
a^{(n)}_{i,j}=
\left \{
\begin{array}{ll}
1 & \hbox{se} \ i=j \ \hbox{o \, se} \ j=n,\\
-1 & \hbox{se} \ i>j,\\
0 & \hbox{altrimenti}
\end{array}
\right .
\qquad
b = A \cdot [1, ..., 1]^T,
$$
per $n = 48 : 2 : 58$ e $b$ scelto in modo che risulti $x = [1, 1, ..., 1]^T$. Che
cosa si osserva?

## Metodi iterativi di Jacobi, Guass-Seidel e Gausseidel_SOR per la soluzione numerica di un sistema lineare

## Esercizio 9
Implementare la  funzione $jacobi(A,b,x0,toll,itmax)$ per risolvere il  sistema lineare Ax=b utilizzando il Metodo iterativo di Jacobi. 
La funzione prende in input:
- A: matrice dei coefficienti
- b: termine noto
- x0: vettore iniziale della stessa dimensione di b
- toll: tolleranza per il criterio di arresto
- itmax: iterazioni massime oltre le quali il metodo si ferma

Calcolare il raggio spettrale della matrice di iterazione.

Implementare un criterio di arresto per il procedimento iterativo in termini di : $||x^{(k)}-x^{(k-1)}||/||x^{(k)}|| <toll$

In [10]:
def jacobi(A, b, x0, toll, it_max):
    n = A.shape[0]

    # estraggo la diagonale delle matrice come array
    d = np.diag(A)
    # costruisco una matrice vuota con diangola 1 / d (inversa di d)
    invM = np.diag(1 / d) 
    # estraggo la triangolare inferriore di A senza la diagonale
    E = np.tril(A, -1)
    # estraggo la traingolare superiore senza di A senza la diagonale
    F = np.triu(A, 1)
    N = -(E + F)

    T = invM @ N
    # il raggio spettrale di T deve essere < 1
    autovalori = npl.eigvals(T)
    # il massimo degli autovalori in valore assoluto
    raggio_spettrale = np.max(np.abs(autovalori))

    if raggio_spettrale >= 1:
        print("Metodo non applicabile")
        return None, None, None
    
    it = 0
    errore = 1000
    err_vet = []
    x = x0

    #q = invM @ b
    
    while it  <= it_max and errore >= toll:
        #x = T @ x0  + q
        x = (b + N @ x0) / d.reshape((n, 1))

        errore = npl.norm(x - x0) / npl.norm(x)
        err_vet.append(errore)

        x0 = x.copy()

        it += 1

    return x, it, err_vet

In [11]:
A = np.array([
    [4,1,3],
    [3,4,1],
    [1,1,17]
])
n = 3
b = np.sum(A, axis=1).reshape((n, 1))

In [12]:
x0 = np.zeros_like(b)
it_max = 500
toll = 1e-8

x, it, err_vet = jacobi(A, b, x0, toll, it_max)
print(x, it)

[[1.]
 [1.]
 [1.]] 35


## Esercizio 10
Implementare la  funzione gauss_seidel(A,b,x0,toll,it_max) per risolvere il  sistema lineare Ax=b utilizzando il Metodo iterativo di Gauss-Seidel. 
La funzione prende in input:
- A: matrice dei coefficienti
- b: termine noto
- x0: vettore iniziale della stessa dimensione di b
- toll: tolleranza per il criterio di arresto
- itmax: iterazioni massime oltre le quali il metodo si ferma

Calcolare il raggio spettrale della matrice di iterazione.

Implementare un criterio di arresto per il procedimento iterativo in termini di : $||x^{(k)}-x^{(k-1)}||/||x^{(k)}|| <toll$

## Esercizio 11
Testare i metodi di Jacobi e di Gauss Seidel nella soluzione dei sistemi lineare Ax=b, dove 
- A=np.array([[4,1,3],[3,4,1],[1,1,17]]) 
- A=np.array([[3,0, 4],[7, 4, 3],[-1, -1 ,-2]])
- A=np.array([[5, 0, -1, 2],[ -2, 4, 1, 0],[0, -1, 4, -1],[ 2, 0, 0, 3]])

ed il termine noto del sistema è scelto in maniera tale che la soluzione esatta del sistema sia il vettore fatto da tutti 1.
Visualizzare in un grafico in scala logaritmica  l'errore per ogni iterazione per ciascun metodo. Cosa si osserva?
Porre toll=1e-8 it_max=500 e x0=np.zeros(A.shape[0]

## Esercizio 12
Implementare la  funzione $gauss$_$seidel$_sor(A,b,x0,omega, toll,itmax) per risolvere il  sistema lineare Ax=b utilizzando il Metodo iterativo di Gauss-Seidel-SOR
La funzione prende in input:
- A: matrice dei coefficienti
- b: termine noto
- x0: vettore iniziale della stessa dimensione di b
- omega: il parametro di rilassamento
- toll: tolleranza per il criterio di arresto
- itmax: iterazioni massime oltre le quali il metodo si ferma

Restituisce in output
- la soluzione x
- l'errore ad ogni iterazione calcolato come $||x^{(k)}-x^{(k-1)}||/||x^{(k)}||$

Calcolare il raggio spettrale della matrice di iterazione.

Implementare un criterio di arresto per il procedimento iterativo in termini di : $||x^{(k)}-x^{(k-1)}||/||x^{(k)}|| <toll$

## Esercizio 13
Scrivere una funzione creaPoisson(n) che preso in input l'ordine della matrice quadrata di Poisson la costruzione secondo la seguente formula:
$$A =
\left [
\begin{array}{ccccccccccc}
4 & -1 & 0 & -1 &0 &0 & 0& 0& \cdots &   0 & 0\\
-1 & 4 & -1 & 0  &-1 &0 & 0& 0& \cdots &   0 & 0\\
0 & -1 & 4 & -1  &0 &-1 & 0& 0& \cdots &   0 & 0 \\
-1 & 0 & -1 & 4  &-1 &0  & -1 & 0& \cdots &   0 & 0\\
0 & -1 & 0 & -1  & 4 &-1 & 0 & -1& \cdots &   0 & 0\\
0 & 0 & -1 & 0  & -1 &4 & -1 & 0&  -1 & 0 & 0 \\
0 & 0 & 0 & \ddots  & 0 &\ddots & \ddots & \ddots& \ddots & \ddots & 0\\
0 & 0 & 0 & 0  & -1 &0  & -1 & 4& -1 &   0& -1\\
\end{array}
 \right ], \qquad
$$
- Risolvere il sistema lineare Ax=b con matrice dei coefficienti A di Poisson di ordine 10 e termine noto b scelto in maniera tale che il sistema abbia soluzione il vettore x con tutte le componenti  uguali ad 1, utilizzando  il metodo iterativo di Jacobi, Gauss-Seidel e Gauss-Seidel-Sor con parametro omega scelto tra 1 e 2 in maniera tale che il raggio spettrale della matrice di iterazione sia il più piccolo possibile e confrontare su un unico grafico l'andamento degli errori in scala logaritmica. Usare toll=1e-10.